ALTER TABLE "Game" ADD COLUMN "appType" TEXT NOT NULL DEFAULT 'unclassified', ADD COLUMN "catalogSource" TEXT, ADD COLUMN "catalogSyncedAt" TIMESTAMP(3), ADD COLUMN "catalogActive" BOOLEAN NOT NULL DEFAULT true, ADD COLUMN "priceChangeNumber" BIGINT, ADD COLUMN "popularityScore" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Store" ADD COLUMN "slug" TEXT, ADD COLUMN "sellerType" TEXT NOT NULL DEFAULT 'unknown', ADD COLUMN "trustStatus" TEXT NOT NULL DEFAULT 'pending', ADD COLUMN "isFirstParty" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "isAuthorized" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "supportedActivationPlatforms" TEXT[] DEFAULT ARRAY[]::TEXT[], ADD COLUMN "officialWebsite" TEXT, ADD COLUMN "verificationSource" TEXT, ADD COLUMN "verifiedAt" TIMESTAMP(3), ADD COLUMN "disabledAt" TIMESTAMP(3), ADD COLUMN "displayPriority" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "Offer" ADD COLUMN "activationPlatform" TEXT NOT NULL DEFAULT 'unknown', ADD COLUMN "purchaseType" TEXT NOT NULL DEFAULT 'unknown';
CREATE TABLE "CatalogSyncRun" ("id" UUID NOT NULL,"provider" TEXT NOT NULL,"status" TEXT NOT NULL,"cursorStart" TEXT,"cursorEnd" TEXT,"fetched" INTEGER NOT NULL DEFAULT 0,"imported" INTEGER NOT NULL DEFAULT 0,"skipped" INTEGER NOT NULL DEFAULT 0,"errorMessage" TEXT,"startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"completedAt" TIMESTAMP(3),CONSTRAINT "CatalogSyncRun_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CatalogSyncCheckpoint" ("id" UUID NOT NULL,"provider" TEXT NOT NULL,"cursor" TEXT,"modifiedSince" BIGINT,"completedCycleAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "CatalogSyncCheckpoint_pkey" PRIMARY KEY ("id"));
CREATE TABLE "StoreVerification" ("id" UUID NOT NULL,"storeId" UUID NOT NULL,"trustStatus" TEXT NOT NULL,"source" TEXT NOT NULL,"evidenceUrl" TEXT,"verifiedAt" TIMESTAMP(3) NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "StoreVerification_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Store_slug_key" ON "Store"("slug"); CREATE INDEX "CatalogSyncRun_provider_startedAt_idx" ON "CatalogSyncRun"("provider","startedAt" DESC); CREATE INDEX "CatalogSyncRun_status_startedAt_idx" ON "CatalogSyncRun"("status","startedAt"); CREATE UNIQUE INDEX "CatalogSyncCheckpoint_provider_key" ON "CatalogSyncCheckpoint"("provider"); CREATE INDEX "StoreVerification_storeId_verifiedAt_idx" ON "StoreVerification"("storeId","verifiedAt" DESC);
ALTER TABLE "StoreVerification" ADD CONSTRAINT "StoreVerification_storeId_fkey" FOREIGN KEY ("storeId") REFERENCES "Store"("id") ON DELETE CASCADE ON UPDATE CASCADE;

UPDATE "Store" SET "slug"='steam',"sellerType"='first_party_store',"trustStatus"='verified',"isFirstParty"=true,"isAuthorized"=true,"supportedActivationPlatforms"=ARRAY['steam'],"officialWebsite"='https://store.steampowered.com',"verificationSource"='cheapshark-store-id-allowlist',"verifiedAt"=CURRENT_TIMESTAMP,"displayPriority"=1 WHERE "provider"='cheapshark' AND "externalId"='1';
UPDATE "Store" SET "slug"='green-man-gaming',"sellerType"='authorized_key_retailer',"trustStatus"='verified',"isAuthorized"=true,"officialWebsite"='https://www.greenmangaming.com',"verificationSource"='cheapshark-store-id-allowlist',"verifiedAt"=CURRENT_TIMESTAMP,"displayPriority"=20 WHERE "provider"='cheapshark' AND "externalId"='3';
UPDATE "Store" SET "slug"='gog',"sellerType"='first_party_store',"trustStatus"='verified',"isFirstParty"=true,"isAuthorized"=true,"supportedActivationPlatforms"=ARRAY['gog'],"officialWebsite"='https://www.gog.com',"verificationSource"='cheapshark-store-id-allowlist',"verifiedAt"=CURRENT_TIMESTAMP,"displayPriority"=3 WHERE "provider"='cheapshark' AND "externalId"='7';
UPDATE "Store" SET "slug"='humble-store',"sellerType"='authorized_key_retailer',"trustStatus"='verified',"isAuthorized"=true,"officialWebsite"='https://www.humblebundle.com/store',"verificationSource"='cheapshark-store-id-allowlist',"verifiedAt"=CURRENT_TIMESTAMP,"displayPriority"=21 WHERE "provider"='cheapshark' AND "externalId"='11';
UPDATE "Store" SET "slug"='fanatical',"sellerType"='authorized_key_retailer',"trustStatus"='verified',"isAuthorized"=true,"officialWebsite"='https://www.fanatical.com',"verificationSource"='cheapshark-store-id-allowlist',"verifiedAt"=CURRENT_TIMESTAMP,"displayPriority"=22 WHERE "provider"='cheapshark' AND "externalId"='15';
UPDATE "Store" SET "slug"='epic-games-store',"sellerType"='first_party_store',"trustStatus"='verified',"isFirstParty"=true,"isAuthorized"=true,"supportedActivationPlatforms"=ARRAY['epic'],"officialWebsite"='https://store.epicgames.com',"verificationSource"='cheapshark-store-id-allowlist',"verifiedAt"=CURRENT_TIMESTAMP,"displayPriority"=2 WHERE "provider"='cheapshark' AND "externalId"='25';
UPDATE "Store" SET "slug"='gamesplanet',"sellerType"='authorized_key_retailer',"trustStatus"='verified',"isAuthorized"=true,"officialWebsite"='https://gamesplanet.com',"verificationSource"='cheapshark-store-id-allowlist',"verifiedAt"=CURRENT_TIMESTAMP,"displayPriority"=23 WHERE "provider"='cheapshark' AND "externalId"='27';
UPDATE "Offer" SET "activationPlatform"='steam',"purchaseType"='direct' WHERE "provider"='cheapshark' AND "storeId" IN (SELECT "id" FROM "Store" WHERE "provider"='cheapshark' AND "externalId"='1');
UPDATE "Offer" SET "activationPlatform"='gog',"purchaseType"='direct' WHERE "provider"='cheapshark' AND "storeId" IN (SELECT "id" FROM "Store" WHERE "provider"='cheapshark' AND "externalId"='7');
UPDATE "Offer" SET "activationPlatform"='epic',"purchaseType"='direct' WHERE "provider"='cheapshark' AND "storeId" IN (SELECT "id" FROM "Store" WHERE "provider"='cheapshark' AND "externalId"='25');
